### ISSUE TITLE
is gitVersion() in build.gradle define anywhere?

### ISSUE THREAD

**Issue by sappusaketh** [trustpilot/kafka-connect-dynamodb#27]
Not seeing any references for custom function `gitVersion()` in `build.gradle`

**Comment by tadeboro** [comment]
Not a gradle expert, it that functions seem to be provided by https://github.com/trustpilot/kafka-connect-dynamodb/blob/50c396cda297faf7ccbfaf3fb19e788d22aabb91/build.gradle#L10
