### ISSUE TITLE
Support for bulk mode along with existing incrementing mode

### ISSUE THREAD

**Issue by NiramayVaidya** [trustpilot/kafka-connect-dynamodb#6]
Incrementing mode for the JDBC source connector only publishes a newly inserted row in a table to the topic based upon an auto-incrementing column.
This source connector goes a step further to also publish a modified row in a table as another record to the topic.
Both these actions can be recorded with the use of DynamoDB Streams since it maintains any kind of changes to the data in the table including inserts and updates for a fixed period of time.
Is there any way to add support for the bulk mode using which every time the connector is started, it publishes all the rows present in a table to the topic?

**Comment by raimondast** [comment]
If I understood you correctly you are referring to "back-filling" support. If so, then yes, backfilling/initial-sync is supported as noted here: https://github.com/trustpilot/kafka-connect-dynamodb#notable-features
